### ISSUE TITLE
Ubuntu 15 error

### ISSUE THREAD

**Issue by FavreNicolas** [appersonlabs/docker.io#41]
```
norfair00@Apollo:~/DotBack/DotAdmin$ sudo npm install docker.io --save
npm WARN package.json dotadmin@1.0.0 No repository field.
npm WARN package.json dotadmin@1.0.0 No README data
 
> node-v8-clone@0.4.5 install /home/norfair00/DotBack/DotAdmin/node_modules/docker.io/node_modules/node-v8-clone
> node-gyp rebuild

make: Entering directory '/home/norfair00/DotBack/DotAdmin/node_modules/docker.io/node_modules/node-v8-clone/build'
  CXX(target) Release/obj.target/clone/src/clone.o
../src/clone.cc:1:0: warning: "BUILDING_NODE_EXTENSION" redefined
 #define BUILDING_NODE_EXTENSION
 ^
<command-line>:0:0: note: this is the location of the previous definition
../src/clone.cc:6:27: error: ‘Arguments’ does not name a type
 Handle<Value> Clone(const Arguments& args) {
                           ^
../src/clone.cc: In function ‘v8::Handle<v8::Value> Clone(const int&)’:
../src/clone.cc:7:28: error: invalid types ‘const int[int]’ for array subscript
   Handle<Value>arg = args[0];
                            ^
In file included from /home/norfair00/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/clone.cc:2:
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/clone.cc:10:17: error: within this context
     HandleScope scope;
                 ^
../src/clone.cc:11:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(obj->Clone());
                  ^
In file included from /home/norfair00/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/clone.cc:2:
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> _DeepClone(v8::Handle<v8::Value>, v8::Local<v8::Object>, v8::Local<v8::Object>)’:
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/clone.cc:18:17: error: within this context
     HandleScope scope;
                 ^
../src/clone.cc:36:33: error: no matching function for call to ‘v8::Array::New()’
       stackMapAArr = Array::New();
                                 ^
../src/clone.cc:36:33: note: candidate is:
In file included from /home/norfair00/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/clone.cc:2:
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:2417:23: note: static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:2417:23: note:   candidate expects 2 arguments, 0 provided
../src/clone.cc:37:33: error: no matching function for call to ‘v8::Array::New()’
       stackMapBArr = Array::New();
                                 ^
../src/clone.cc:37:33: note: candidate is:
In file included from /home/norfair00/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/clone.cc:2:
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:2417:23: note: static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:2417:23: note:   candidate expects 2 arguments, 0 provided
../src/clone.cc:53:20: error: ‘class v8::HandleScope’ has no member named ‘Close’
       return scope.Close(cloned);
                    ^
../src/clone.cc:61:49: error: no matching function for call to ‘v8::Integer::New(unsigned int&)’
       Local<Value> key(props->Get(Integer::New(i)));
                                                 ^
../src/clone.cc:61:49: note: candidate is:
In file included from /home/norfair00/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/clone.cc:2:
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/clone.cc:67:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(cloned);
                  ^
../src/clone.cc: At global scope:
../src/clone.cc:72:31: error: ‘Arguments’ does not name a type
 Handle<Value> DeepClone(const Arguments& args) {
                               ^
../src/clone.cc: In function ‘v8::Handle<v8::Value> DeepClone(const int&)’:
../src/clone.cc:73:27: error: invalid types ‘const int[int]’ for array subscript
   return _DeepClone(args[0], Object::New(), Object::New());
                           ^
../src/clone.cc:73:42: error: no matching function for call to ‘v8::Object::New()’
   return _DeepClone(args[0], Object::New(), Object::New());
                                          ^
../src/clone.cc:73:42: note: candidate is:
In file included from /home/norfair00/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/clone.cc:2:
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:2388:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../src/clone.cc:73:57: error: no matching function for call to ‘v8::Object::New()’
   return _DeepClone(args[0], Object::New(), Object::New());
                                                         ^
../src/clone.cc:73:57: note: candidate is:
In file included from /home/norfair00/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/clone.cc:2:
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:2388:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../src/clone.cc: In function ‘void Init(v8::Handle<v8::Object>)’:
../src/clone.cc:77:15: error: ‘NewSymbol’ is not a member of ‘v8::String’
   target->Set(String::NewSymbol("clone"),
               ^
../src/clone.cc:78:34: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
       FunctionTemplate::New(Clone)->GetFunction());
                                  ^
../src/clone.cc:78:34: note: candidate is:
In file included from /home/norfair00/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/clone.cc:2:
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../src/clone.cc:79:15: error: ‘NewSymbol’ is not a member of ‘v8::String’
   target->Set(String::NewSymbol("deepclone"),
               ^
../src/clone.cc:80:38: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
       FunctionTemplate::New(DeepClone)->GetFunction());
                                      ^
../src/clone.cc:80:38: note: candidate is:
In file included from /home/norfair00/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/clone.cc:2:
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/norfair00/.node-gyp/0.12.7/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../src/clone.cc: In function ‘v8::Handle<v8::Value> DeepClone(const int&)’:
../src/clone.cc:74:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
clone.target.mk:85: recipe for target 'Release/obj.target/clone/src/clone.o' failed
make: *** [Release/obj.target/clone/src/clone.o] Error 1
make: Leaving directory '/home/norfair00/DotBack/DotAdmin/node_modules/docker.io/node_modules/node-v8-clone/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.0-28-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/norfair00/DotBack/DotAdmin/node_modules/docker.io/node_modules/node-v8-clone
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.19.0-28-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "docker.io" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! node-v8-clone@0.4.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-v8-clone@0.4.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-v8-clone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-v8-clone
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/norfair00/DotBack/DotAdmin/npm-debug.log
```

**Comment by drorm** [comment]
Also on 14.04.  This project is out of date.
Use https://github.com/apocas/dockerode instead
